
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: ipam.metal3.io/v1alpha1
kind: IPPool
metadata:
  name: pool1
  namespace: ${NAMESPACE}
spec:
  namePrefix: pool1-prov
  pools:
  - start: 192.168.0.10
    end: 192.168.0.50
    prefix: 24
    gateway: 192.168.0.1
---
apiVersion: ipam.metal3.io/v1alpha1
kind: IPClaim
metadata:
  name: provisioning-pool
  namespace: ${NAMESPACE}
spec:
  pool:
    name: pool1
    namespace: ${NAMESPACE}
---
apiVersion: ipam.cluster.x-k8s.io/v1beta2
kind: IPAddressClaim
metadata:
  name: provisioning-pool
  namespace: ${NAMESPACE}
spec:
  poolRef:
    apiGroup: ipam.metal3.io
    kind: IPPool
    name: pool1
