name: build-images-action

on:
  push:
    branches:
    - 'main'
    - 'release-*'
    tags:
    - 'v*'

permissions:
  contents: read

jobs:
  build_ipam:
    name: Build IPAM container image
    if: github.repository == 'metal3-io/ip-address-manager'
    permissions:
      contents: read
      id-token: write
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main # zizmor: ignore[unpinned-uses]
    with:
      image-name: 'ip-address-manager'
      pushImage: true
      generate-sbom: true
      sign-image: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
